Class {
	#name : 'TournamentDraw',
	#superclass : 'TournamentOutcome',
	#category : 'Exercise@Tournament',
	#package : 'Exercise@Tournament'
}

{ #category : 'numeric' }
TournamentDraw >> d [
	^ 1
]

{ #category : 'path commands' }
TournamentDraw >> l [
	^ 0
]

{ #category : 'accessing' }
TournamentDraw >> points [
	^ 1.
]

{ #category : 'accessing - structure variables' }
TournamentDraw >> w [
	^ 0
]
