Class {
	#name : 'TournamentLoss',
	#superclass : 'TournamentOutcome',
	#category : 'Exercise@Tournament',
	#package : 'Exercise@Tournament'
}

{ #category : 'numeric' }
TournamentLoss >> d [
	^ 0
]

{ #category : 'path commands' }
TournamentLoss >> l [
	^ 1
]

{ #category : 'accessing' }
TournamentLoss >> points [
	^ 0
]

{ #category : 'accessing - structure variables' }
TournamentLoss >> w [
	^ 0
]
