name: Pharo track CI

on:
  push:
    branches: [main]
  pull_request:


jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [Pharo64-12,  Pharo64-11]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - uses: hpi-swa/setup-smalltalkCI@c13cd871b26372e1028c94d5d6af67a8677f1e79
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
